---
- name: copying the auditd exporter binary file
  become: true
  copy:
    src: linux-auditd-exporter
    dest: /usr/local/bin
    mode: 0755

- name: auditd exporter | Create Unit file
  template: src=auditd-exporter.service.j2 dest=/etc/systemd/system/auditd-exporter.service mode=644
  notify:
    - reload systemctl

- name: audit exporter | Start auditd exporter
  service: name=auditd-exporter.service state=started enabled=yes
